.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 28 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 35 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 36 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 37 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 38 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 39 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 40 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 41 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 42 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 43 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 44 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 45 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 46 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 47 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 48 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 49 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 50 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 51 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 52 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 53 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 54 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 55 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 56 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 57 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 58 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 59 --fragment_id all
.\.venv\Scripts\python.exe  main.py --script rdp_to_csv_per_piece --group 60 --fragment_id all